---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ghcr.io/${{ github.repository }}
  CONTAINER_COMMIT_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  CONTAINER_LATEST_IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:
  lint-all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast:
    name: Static Code Analysis Tests
    runs-on: ubuntu-latest
    needs:
      - lint-all
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run static code analysis
        run: |
          pip3 install -r requirements.txt
          bandit app.py

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - sast
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run unit tests
        run: |
          pip3 install -r requirements.txt
          python -m pytest

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Build
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push Docker image
        run: |
          docker build --build-arg APP_VERSION="$APP_VERSION" -t $CONTAINER_COMMIT_IMAGE  -t $CONTAINER_LATEST_IMAGE .
          docker push $CONTAINER_COMMIT_IMAGE
          docker push $CONTAINER_LATEST_IMAGE
        env:
          APP_VERSION: ${{ github.sha }}

  integ-tests:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Integ Tests
    runs-on: ubuntu-latest
    needs:
      - build
    services:
      my-app:
        image: ghcr.io/${{ github.repository }}:${{ github.sha }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v3

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - run: ./github-actions-scripts/test_bats.sh
