---
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CONTAINER_REGISTRY: ghcr.io/augustin-ardon/github-actions-dojo
  CONTAINER_COMMIT_IMAGE: ghcr.io/augustin-ardon/github-actions-dojo:${{ github.sha }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag name
        id: tagName
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      
      - name: Login to Github Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Docker image
        run: |
          docker pull "$CONTAINER_COMMIT_IMAGE"
          docker tag "$CONTAINER_COMMIT_IMAGE" "$CONTAINER_REGISTRY:$TAG"
          docker push "$CONTAINER_REGISTRY:$TAG"
        env:
          TAG: ${{ steps.tagName.outputs.tag }}
